# IMPLEMENTATION STATUS: Stub
#
# This tool returns empty/default results when no baseline file is
# configured. A production implementation would query stored behavioral
# baselines for a given username to return:
#   - normal authentication hours
#   - normal device count
#   - normal NAS pool
#   - historical failure rate
#
# Baselines are generated by the ISE-DFP training pipeline and stored
# in the scaler.json artifact. A full implementation would load that
# artifact and expose per-user baseline statistics here.

"""Baseline comparison tool — compares current traffic against stored baselines."""

import json
import logging
import os
import time

logger = logging.getLogger(__name__)

BASELINE_PATH = os.environ.get("BASELINE_PATH", "baselines.json")
DEFAULT_TIMEOUT = int(os.environ.get("TOOL_TIMEOUT", "30"))

_baseline_cache = None


def _load_baselines():
    global _baseline_cache
    if _baseline_cache is not None:
        return _baseline_cache
    try:
        with open(BASELINE_PATH, "r") as f:
            _baseline_cache = json.load(f)
        return _baseline_cache
    except (FileNotFoundError, json.JSONDecodeError) as e:
        logger.debug("Failed to load baselines: %s", e)
        return {}


def run(ip: str, metric: str = "bytes_per_hour", current_value: float = 0.0,
        timeout: int = DEFAULT_TIMEOUT) -> dict:
    """Compare an IP's current metric against stored baseline."""
    tool_name = "baseline_query"
    start = time.monotonic()

    try:
        baselines = _load_baselines()

        ip_baseline = baselines.get(ip, baselines.get("default", {}))
        metric_baseline = ip_baseline.get(metric, {})

        mean = metric_baseline.get("mean", 0)
        std = metric_baseline.get("std", 1)

        # Calculate deviation
        deviation = abs(current_value - mean) / std if std > 0 else 0
        is_anomalous = deviation > 2.0  # 2 sigma threshold

        result = {
            "ip": ip, "metric": metric,
            "current_value": current_value,
            "baseline_mean": mean, "baseline_std": std,
            "deviation_sigma": round(deviation, 2),
            "is_anomalous": is_anomalous,
        }

        duration = int((time.monotonic() - start) * 1000)
        return {"tool_name": tool_name, "success": True, "result": result,
                "error": None, "duration_ms": duration}
    except Exception as e:
        duration = int((time.monotonic() - start) * 1000)
        return {"tool_name": tool_name, "success": False, "result": None,
                "error": str(e), "duration_ms": duration}
